Repository ArcBlock/forge-cli, pull requests merged in 2019-09, with the labels that each got.

#216 fix not exit process when upgrade failed
  CHANGELOG.md
  package.json
  src/cli/node/start/start.js
  src/cli/node/upgrade/upgrade.js
  version
Labels: area/ux

#233 Fix: use asset list from remote
  CHANGELOG.md
  package.json
  src/cli/node/install/install.js
  src/cli/release/download/download.js
  src/cli/release/download/lib.js
  src/cli/release/use/use.js
  src/core/util.js
  version
Labels: priority/important-soon

#241 Feat: support config a multi node chain
  CHANGELOG.md
  package.json
  src/cli/blocklet/use/use.js
  src/cli/node/index.js
  src/cli/node/prepare/index.js
  src/cli/node/prepare/prepare.js
  src/constant.js
  src/core/forge-config.js
  version
  yarn.lock
Labels: area/client

#242 fix: 'forge ls/upgrade/ls:remote' list incomplete releases #239
  CHANGELOG.md
  package.json
  src/cli/misc/version/version.js
  src/cli/node/install/install.js
  src/cli/node/upgrade/upgrade.js
  src/cli/release/download/download.js
  src/cli/release/list/list.js
  src/cli/release/remote/remote.js
  src/cli/release/use/use.js
  src/constant.js
  src/core/env.js
  src/core/forge-config.js
  src/core/forge-fs.js
  src/core/util.js
  version
Labels: area/ux

#254 no longer create a default chain before execute every command
  CHANGELOG.md
  package.json
  src/cli/account/create/index.js
  src/cli/account/delete/index.js
  src/cli/account/display/index.js
  src/cli/account/list/index.js
  src/cli/blocklet/use/index.js
  src/cli/chain/create/index.js
  src/cli/chain/list/index.js
  src/cli/chain/list/list.js
  src/cli/chain/remove/index.js
  src/cli/chain/remove/remove.js
  src/cli/misc/create/create.js
  src/cli/misc/create/templates/.makefile
  src/cli/misc/create/templates/index.js.tpl
  src/cli/misc/help/index.js
  src/cli/misc/version/index.js
  src/cli/misc/version/version.js
  src/cli/node/config/lib.js
  src/cli/node/install/index.js
  src/cli/node/install/install.js
  src/cli/node/logs/index.js
  src/cli/node/ps/index.js
  src/cli/node/start/index.js
  src/cli/node/stop/index.js
  src/cli/node/stop/stop.js
  src/cli/node/upgrade/index.js
  src/cli/protocol/compile/index.js
  src/cli/release/download/index.js
  src/cli/release/list/list.js
  src/cli/release/remote/index.js
  src/cli/release/use/index.js
  src/cli/release/use/use.js
  src/cli/wallet/create/index.js
  src/core/cli.js
  src/core/env.js
  src/core/forge-config.js
  src/core/forge-fs.js
  src/core/forge-process.js
  src/core/libs/common.js
  src/core/libs/interaction.js
  src/core/util.js
  src/index.js
  version
Labels: priority/important-soon, priority/release-blocker
